// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/creditLines": {
            "get": {
                "description": "get all creditLines",
                "tags": [
                    "creditLine"
                ],
                "summary": "Get all creditLines",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.CreditLine"
                            }
                        }
                    }
                }
            },
            "post": {
                "description": "Create a creditLine",
                "consumes": [
                    "application/json"
                ],
                "tags": [
                    "creditLine"
                ],
                "summary": "Create a creditLine",
                "parameters": [
                    {
                        "description": "creditLine Data",
                        "name": "creditLine",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.CreditLineRequestBody"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ResponseBody"
                        }
                    }
                }
            }
        },
        "/creditLines/{id}": {
            "get": {
                "description": "Get a creditLine by id",
                "tags": [
                    "creditLine"
                ],
                "summary": "Get a creditLine by id",
                "parameters": [
                    {
                        "type": "string",
                        "description": "creditLine ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.CreditLine"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.CreditLine": {
            "type": "object",
            "properties": {
                "allowedRequest": {
                    "type": "boolean"
                },
                "attemptAcceptedNumber": {
                    "type": "integer"
                },
                "attemptNumber": {
                    "type": "integer"
                },
                "cashBalance": {
                    "type": "number"
                },
                "foundingName": {
                    "type": "string"
                },
                "foundingType": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "lastAcceptedRequestDate": {
                    "type": "string"
                },
                "monthlyRevenue": {
                    "type": "number"
                },
                "recommendedCreditLine": {
                    "type": "number"
                },
                "requestedCreditLine": {
                    "type": "number"
                },
                "requestedDate": {
                    "type": "string"
                },
                "requestedServerDate": {
                    "type": "string"
                },
                "state": {
                    "type": "string"
                }
            }
        },
        "models.CreditLineRequestBody": {
            "type": "object",
            "properties": {
                "cashBalance": {
                    "type": "number"
                },
                "foundingName": {
                    "type": "string"
                },
                "foundingType": {
                    "type": "string"
                },
                "monthlyRevenue": {
                    "type": "number"
                },
                "requestedCreditLine": {
                    "type": "number"
                },
                "requestedDate": {
                    "type": "string"
                }
            }
        },
        "models.CreditLineResponseBody": {
            "type": "object",
            "properties": {
                "cashBalance": {
                    "type": "number"
                },
                "foundingName": {
                    "type": "string"
                },
                "foundingType": {
                    "type": "string"
                },
                "monthlyRevenue": {
                    "type": "number"
                },
                "recommendedCreditLine": {
                    "type": "number"
                },
                "requestedCreditLine": {
                    "type": "number"
                },
                "requestedDate": {
                    "type": "string"
                },
                "requestedServerDate": {
                    "type": "string"
                }
            }
        },
        "models.ResponseBody": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/models.CreditLineResponseBody"
                },
                "error": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Gin Swagger Example API",
	Description:      "This is a sample server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
