basePath: /
host: localhost:8080
info:
  contact: {}
  description: This is a sample server.
  title: Gin Swagger Example API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - '*/*'
      description: get the status of server.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
      - root
  /creditLine:
    get:
      description: get all people
      responses: {}
      summary: Get all people
      tags:
      - creditLine
  /people:
    get:
      description: get all people
      responses: {}
      summary: Get all people
      tags:
      - people
schemes:
- http
swagger: "2.0"
