basePath: /
definitions:
  models.CreditLine:
    properties:
      allowedRequest:
        type: boolean
      attemptAcceptedNumber:
        type: integer
      attemptNumber:
        type: integer
      cashBalance:
        type: number
      foundingName:
        type: string
      foundingType:
        type: string
      id:
        type: integer
      lastAcceptedRequestDate:
        type: string
      monthlyRevenue:
        type: number
      recommendedCreditLine:
        type: number
      requestedCreditLine:
        type: number
      requestedDate:
        type: string
      state:
        type: string
    type: object
  models.CreditLineRequestBody:
    properties:
      cashBalance:
        type: number
      foundingName:
        type: string
      foundingType:
        type: string
      monthlyRevenue:
        type: number
      requestedCreditLine:
        type: number
    type: object
  models.CreditLineResponseBody:
    properties:
      cashBalance:
        type: number
      foundingName:
        type: string
      foundingType:
        type: string
      monthlyRevenue:
        type: number
      recommendedCreditLine:
        type: number
      requestedCreditLine:
        type: number
      requestedDate:
        type: string
    type: object
  models.ResponseBody:
    properties:
      data:
        $ref: '#/definitions/models.CreditLineResponseBody'
      error:
        type: string
      message:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: API that calculates a recommended creditLine for a Founding based on
    its type and other fields.
  title: The Credit Line API
  version: "1.0"
paths:
  /creditLines:
    post:
      consumes:
      - application/json
      description: Create a creditLine
      parameters:
      - description: creditLine Data
        in: body
        name: creditLine
        required: true
        schema:
          $ref: '#/definitions/models.CreditLineRequestBody'
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.ResponseBody'
      summary: Create a creditLine
      tags:
      - creditLine
  /creditLines/foundingName/{foundingName}:
    get:
      description: Get all the creditLines requests a foundingName did
      parameters:
      - description: creditLine foundingName
        in: path
        name: foundingName
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.CreditLine'
            type: array
      summary: Get all the creditLines requests a foundingName did
      tags:
      - creditLine
schemes:
- http
swagger: "2.0"
